### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by dorbittonn** [Chiang97912/bet365.com#11]
Hey!

# Installation
git clone https://github.com/Chiang97912/bet365.com.git
pip3 install -r bet365.com/requeriments.txt --user

Should I paste those lines in a linux-bash-shell or in a python Terminal?

**Comment by Chiang97912** [comment]
Yes, The function of those lines just to clone this repo to local and install the requeriments of this repo.

**Comment by dorbittonn** [comment]
Thanks for super fast answer! 
but my terminal does not recognize the command "git"

**Comment by dorbittonn** [comment]
why did you close it

**Comment by Chiang97912** [comment]
This is the most basic knowledge, please submit a meaningful issue.
