### ISSUE TITLE
Pstk cookie issue

### ISSUE THREAD

**Issue by dochenaj** [Chiang97912/bet365.com#15]
I get the cookie the first time but on repeat runs of the script. It never receives that header.

And on such occasions when the cookie is not sent, the server redirects the request to localhost. I supposed, this was an IP blocking issue but it also happens with my local IP which can still access the website on the browser.

But the problem is more pronounced on my VPS that has a UK IP address.

I have done a lot of tweaking on the headers, yet to no avail.

**Comment by HMaker** [comment]
They return HTTP 400, 500 or 200 with empty response when headers are wrong. If that problem also happens with your local IP but you can access their website on the browser, then use the browser to inspect the network traffic and check if their API has changed.

**Comment by dochenaj** [comment]
@HMaker, I wonder how headers can be wrong. What do you suppose constitute a wrong header?
My biggest challenge is that the problem is random, with the same headers it works for sometimes and doesn't work at other times.

**Comment by HMaker** [comment]
Wrong headers means missing headers or invalid values. I have never seen redirections due to wrong headers yet.
Which endpoint you are acessing? I think you should show some code.

**Comment by dochenaj** [comment]
def get_session_id():
    headers={
        "Host" : "www.bet365.com",
        "User-Agent": USER_AGENT,
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "Origin": "https://www.bet365.com",
        "Upgrade-Insecure_Requests": "1",
        "Cache-Control": "max-age=500",
        "Accept-Language" : "en-US,en;q=0.9",
        "Accept-Encoding" : "gzip, deflate,br",
        "Referer" : "https://www.bet365.com/",
        "Connection" : "keep-alive",
        "Cookie" : "aps03=ct=197&lng=1",
    }
    url = 'https://www.bet365.com/defaultapi/sports-configuration'
    response = requests.get(url=url, headers=headers)
    try:
        session_id = response.cookies['pstk']
    except:
        print('Session cookie not found')
    print (session_id)
    return session_id

**Comment by HMaker** [comment]
Check if `response.url` is `https://www.bet365.com/defaultapi/sports-configuration` and `response.status_code` is `200`. You can check [Response.history](https://requests.readthedocs.io/en/master/api/#requests.Response.history) to see if you are being redirected.

**Comment by dochenaj** [comment]
When it fails, response.url is http://localhost. 

What worries me is that without changing the code in any way, it works sometimes and other times doesn't work. I can't figure out why this is happening. My guess is that it is probably a bet365 server issue.

Like I pointed out, the initial request returns a 302 response redirecting to http://localhost.com

**Comment by HMaker** [comment]
Do you also have that redirections to localhost on browser? If so, I think your IP address is blacklisted.

**Comment by dochenaj** [comment]
I thought that too. But if the IP was blacklisted, it shouldn't be able work at all.
