### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by lvlira** [Chiang97912/bet365.com#19]
Hi guys, I'm in Brazil and I want to follow some football games here. I used this code today and put it to run without modifying any part of the code. That didn't work. The code is frozen in 'updateGameData'. If that had worked, I would parse and change the code to "pt-br" and use the string "Futebol" instead of "football".

**Comment by HMaker** [comment]
This code is outdated, read #9 to know the reasons and possible ways to fix it.
