### ISSUE TITLE
KeyError: "name='pstk', domain=None, path=None"

### ISSUE THREAD

**Issue by 1912george** [Chiang97912/bet365.com#4]
The get_session_id() throws a KeyError:

KeyError: "name='pstk', domain=None, path=None"

**Comment by Chiang97912** [comment]
Try to replace the url which in the function of get_session_id with 'https://www.288365.com/defaultapi/sports-configuration'. And later I will update the code and push it into github!

**Comment by 1912george** [comment]
yes, seems to be working with the new url. Thanks!

**Comment by Vince3453463** [comment]
I am getting the same error, even though the new url is already in the code

**Comment by crclayton** [comment]
Same issue here

**Comment by ChenHY1992** [comment]
The same problem occurs with this url 'https://[www.288365.com](https://www.288365.com/defaultapi/sports-configuration)/defaultapi/sports-configuration'

**Comment by ihor2005** [comment]
> The same problem occurs with this url 'https://[www.288365.com](https://www.288365.com/defaultapi/sports-configuration)/defaultapi/sports-configuration'

Sorry, which error you are talking about ? I am getting odds from bet365 Ok
